---
title: "R Notebook"
output: html_notebook
---

```{r}
# R package for pulling in song lyrics
library(geniusR) 
# collection of tidy data analysis pacakages
library(tidyverse)
# Tidy text manipulations
library(tidytext)

# Scape the lyrics for my Trap House 3
Gucci <- genius_album(artist = "Gucci Mane", album = "Trap House 3")
```

```{r}
# anti_join to remove stop words
tidy_Gucci <- Gucci %>%
  unnest_tokens(word,lyric) %>%
  anti_join(stop_words)
```

```{r}
song_words <- tidy_Gucci %>%
  count(track_title, word, sort = TRUE) %>%
  ungroup()
```

```{r}
song_words <- song_words %>%
  bind_tf_idf(word, track_title, n) %>%
  arrange(desc(tf_idf))

head(song_words)
```

```{r}

library(ggthemes)
df = song_words %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>%
  group_by(track_title) %>%
  top_n(5) %>%
  ungroup() 



 plot1 = df %>%  ggplot(aes(word, tf_idf, fill = track_title)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~track_title, ncol = 2, scales = "free") +
  theme_fivethirtyeight()
 ggsave("gucci.png", plot1, height = 14, width = 14)
```

